version: '3.8'
services:
  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
  urlservice:
    build: .
    restart: on-failure
    container_name: urlservice
    ports:
      - '9011:9011'
    environment:
      SPRING_APPLICATION_JSON: '{
        "mongo.connection.string"  : "mongodb+srv://admin:admin@urlmapping.bmlheqk.mongodb.net/?retryWrites=true&w=majority",
        "mongodb.database.name" : "URLMapping",
        "config.http.read.timeout" : "2",
        "config.http.connection.timeout" : "2",
        "config.node.id" : "n1",
        "config.range.url" : "http://tokenservice:8088/range/",
        "server.port":"9011",
        "server.address":"0.0.0.0",
        "spring.redis.host":"localhost",
        "spring.redis.port":"6379"
      }'
    volumes:
      - .m2:/root/.m2
    stdin_open: true
    tty: true